- name: variables to print
  hosts: web
  vars:
    COURSE: "DevOps with Aws"
    DURATIION: "120HRS"
    TRAINER: "Siva"
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}},Duration is: {{DURATION}}, Trainer: {{TRAINER}}"