- name: variables from files
  hosts: web
  vars_files:
  - vars.yaml
  tasks:
  - name: print the course information
    ansible.builtin.dbugg:
      msg: "Hi, i am learning {{COURSE}},Duration is: {{DURATION}}, Trainer: {{TRAINER}}"