- name: vars from inventory
  hosts: web
  vars_inventory:
  tasks:
  - name: Print Course Detailes
  ansible.builtin.debug:
     msg: "Hi i am learning {{COURSE}}, Duration is: {{DURATION}}, Trainer is: {{TRAINER}}"