- name: check a number is less than 10 or not
  hosts: local
  connection: local
  vars_prompt: 
  - name: my_number
    prompt: Please enter the number
    private: false #not confidential
  # vars:
  #   my_number: 139 #number
  tasks:
  - name: print this if less than 10
    ansible.builtin.debug:
        msg: "Given number {{ my_number }} is less than 10"
    when: my_number | int < 10 # conditional expression

  - name: print this if greater than or equal to 10
    ansible.builtin.debug:
        msg: "Given number {{ my_number }} is greater than 10"
    when: my_number | int >= 10


# usage command "ansible-playbook -i inventory.ini 12-conditions.yaml 
#Please enter the number: 5 "