- name: create user
  hosts: web
  become: yes
  tasks:
  - name: check user exit or not
    ansible.builtin.command: id expence
    register: USER #here USER is a variable that gets output from above command 
    ignore_errors: true

  - name: print the user information
    ansible.builtin.debug:
        msg: "user info: {{ USER }}"


  - name: create user
    ansible.builtin.command: useradd expence
    when: USER.rc != 0
    