- name: demo on filters/functions
  hosts: local
  connection: local
  tasks:
  - name: print the default variables
    ansible.builtin.debug:
        msg: "Hello {{ course | default('Ansible') }}"


  - name: convert to uppercase
    vars:
      greeting: "Hello Ramesh"
    ansible.builtin.debug:
        msg: "{{ greeting | upper }}"

  - name: converting to lowercase
    vars:
      greeting: "Hello Ramesh"
    ansible.builtin.debug:
        msg: "{{ greeting | lower }}"