- name: create ec2 and r53 recrods
  hosts: local
  connection: local
  vars:
     subnet_id: "subnet-09ac78b23ac4eae54"
     sg_id: "sg-04171accc0f35de44"
     ami_id: "ami-09c813fb71547fc4f"
     instances:
     - mysql
     - backend
     - frontend
  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
    loop: "{{ instances }}"
    register: ec2_instances
  - name: print the output
    ansible.builtin.debug:
        msg: "{{ ec2_instances }}"

  # - name: create route53 records
  #   amazon.aws.route53:
  #      state: present
  #      zone: manibhumaraju.online